services:
  mc:
    image: itzg/minecraft-server:java21
    container_name: mc-neoforge
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TZ: "America/Chicago"
      MEMORY: "12G"

      # Install from your hosted .mrpack (auto-installs loader; updates on container start)
      TYPE: "MODRINTH"
      MODRINTH_MODPACK: "https://github.com/lshoy/bronnypack/releases/latest/download/BronnyPack.mrpack?nocache=${MRPACK_NOCACHE}"

      # Server access
      ENABLE_RCON: "TRUE"
      RCON_PASSWORD: "poopscoop2"

      ALLOW_FLIGHT: "TRUE"

      # Bump this to force a fresh download of the .mrpack (avoids CDN caching)
      MRPACK_NOCACHE: "2025-10-12-1"

      # Avoid pruning/removing files not in the modpack (preserve local configs)
      MODRINTH_FORCE_SYNCHRONIZE: "false"

      # Turn off the image’s built-in include/exclude heuristics
      MODRINTH_DEFAULT_EXCLUDE_INCLUDES: ""

      # Auto-enable AllTheMons datapack on NEW worlds (expects world/datapacks/AllTheMons.zip)
      INITIAL_ENABLED_PACKS: "vanilla, file/AllTheMons"

      # Auto-install AllTheMons datapack into the CURRENT world's datapacks folder
      DOWNLOAD_URLS: |
        https://cdn.modrinth.com/data/JV5dvqVX/versions/ulwWbVUc/AllTheMons%20Release%202.4.zip -> /data/world/datapacks/AllTheMons.zip

      # Auto-enable the datapack on server start (for existing world)
      RCON_CMDS_STARTUP: |
        datapack enable "file/AllTheMons"
        reload

      # Distribute the AllTheMons resource pack to clients (direct CDN url + SHA1 recommended)
      RESOURCE_PACK: "https://cdn.modrinth.com/data/JV5dvqVX/versions/ulwWbVUc/AllTheMons%20Release%202.4.zip"
      RESOURCE_PACK_SHA1: "B4C519A3620D036C17B7DAA20D44B962E9B32A9B"

      # Exclude only the client-only mods actually in your mrpack (newline-separated partial names)
      MODRINTH_EXCLUDE_FILES: |
        athena-
        betterbeaconeffects-
        BetterF3-
        chat_heads-
        cobblemon-ui-tweaks-
        CobblemonMoveInspector-
        continuity-
        controlling-
        distraction_free_recipes-
        emoji-type-
        enchdesc-
        fusion-
        Handful-
        hidehands-
        iris-
        ismah-
        jei_integration_reborn-
        justenoughbreeding-
        LongerChatHistory-
        MaidTaskScroll-
        modelfix-
        MoreCobblemonTweaks-
        MouseTweaks-
        music_player-
        Neat-
        notenoughanimations-
        Notes-
        particlerain-
        skinlayers3d-
        sodium-
        XaeroZoomout-
        zume-
        # Also exclude local server configs from being overwritten by modpack overrides
        config/cobblemon/main.json
        config/rctmod-server.toml
 
      # skip temp connector jars bundled in overrides, if present
      MODRINTH_OVERRIDES_EXCLUSIONS: |
        mods/.connector/**
        config/**
    volumes:
      - ./data:/data
    restart: unless-stopped
    stop_grace_period: 2m
