services:
  # 1) One-shot backup that must complete BEFORE the server starts
  prebackup:
    image: alpine:3
    container_name: mc-prebackup
    restart: "no"
    environment:
      TZ: "America/Chicago"
    volumes:
      - ./data:/data:ro        # read-only snapshot of the server data
      - ./backups:/backups     # backups will be written here
    entrypoint: ["/bin/sh","-c"]
    command: >
      set -e;
      mkdir -p /backups;
      ts=$(date +%Y%m%d-%H%M%S);
      echo "==> Creating pre-start backup /backups/prestart-$ts.tgz";
      tar -czf /backups/prestart-$ts.tgz
        --exclude='*.jar' --exclude='cache' --exclude='logs' --exclude='*.tmp'
        -C /data .

  mc:
    image: itzg/minecraft-server:java21
    container_name: mc-neoforge
    depends_on:
      prebackup:
        condition: service_completed_successfully  # wait for backup to finish
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TZ: "America/Chicago"
      MEMORY: "12G"

      # Install from your hosted .mrpack (auto-installs loader; updates on container start)
      TYPE: "MODRINTH"
      MODRINTH_MODPACK: "https://github.com/lshoy/bronnypack/releases/latest/download/BronnyPack.mrpack"

      # Server access
      ENABLE_RCON: "TRUE"
      RCON_PASSWORD: "poopscoop2"

      # Make the sync deterministic
      MODRINTH_FORCE_SYNCHRONIZE: "true"

      # Turn off the image’s built-in include/exclude heuristics
      MODRINTH_DEFAULT_EXCLUDE_INCLUDES: ""

      # Exclude only the client-only mods actually in your mrpack (newline-separated partial names)
      MODRINTH_EXCLUDE_FILES: |
        athena-
        betterbeaconeffects-
        BetterF3-
        chat_heads-
        cobblemon-ui-tweaks-
        CobblemonMoveInspector-
        continuity-
        distraction_free_recipes-
        emoji-type-
        enchdesc-
        fusion-
        Handful-
        hidehands-
        iris-
        ismah-
        jei_integration_reborn-
        justenoughbreeding-
        LongerChatHistory-
        MaidTaskScroll-
        modelfix-
        MoreCobblemonTweaks-
        MouseTweaks-
        music_player-
        Neat-
        notenoughanimations-
        Notes-
        particlerain-
        skinlayers3d-
        sodium-
        XaeroZoomout-
        zume-
 
      # skip temp connector jars bundled in overrides, if present
      MODRINTH_OVERRIDES_EXCLUSIONS: |
        mods/.connector/**
    volumes:
      - ./data:/data
    restart: unless-stopped
    stop_grace_period: 2m
