services:
  mc:
    image: itzg/minecraft-server:java21
    container_name: mc-neoforge
    entrypoint: [/data/refresh-wrapper.sh]
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TZ: "America/Chicago"
      MEMORY: "12G"

      # --- Modpack from your hosted .mrpack (cache-bust supported, no .env needed) ---
      TYPE: "MODRINTH"
      MODRINTH_MODPACK: "https://github.com/lshoy/bronnypack/releases/latest/download/BronnyPack.mrpack?nocache=${MRPACK_NOCACHE:-0}"

      # Bump this to force "modpack refresh" logic when desired; manifest-based refresh in pre-init clears
      # /data/mods automatically when the published modpack version changes.
      MRPACK_NOCACHE: "3"

      # Explicit world folder name for datapack path
      LEVEL: "world"

      ALLOW_FLIGHT: "TRUE"

      # Always re-evaluate the mrpack manifest (mods update/remove as needed)
      MODRINTH_FORCE_SYNCHRONIZE: "true"

      # Never let overrides touch persisted configs or datapacks
      MODRINTH_OVERRIDES_EXCLUSIONS: |
        config/**
        world/datapacks/**

      # Drop client-only mods by partial jar names (optional list retained)
      MODRINTH_EXCLUDE_FILES: |
        athena-
        betterbeaconeffects-
        BetterF3-
        chat_heads-
        cobblemon-ui-tweaks-
        CobblemonMoveInspector-
        continuity-
        controlling-
        distraction_free_recipes-
        emoji-type-
        enchdesc-
        fusion-
        Handful-
        hidehands-
        iris-
        ismah-
        jei_integration_reborn-
        justenoughbreeding-
        LongerChatHistory-
        MaidTaskScroll-
        modelfix-
        MoreCobblemonTweaks-
        MouseTweaks-
        music_player-
        Neat-
        notenoughanimations-
        Notes-
        particlerain-
        skinlayers3d-
        sodium-
        vinurl-
        XaeroZoomout-
        zume-

      # Fetch and place AllTheMons datapack for the existing world
      DOWNLOAD_EXTRA_CONFIGS: |
        world/datapacks<https://cdn.modrinth.com/data/qoL4kNxC/versions/4i8KszCj/CCC_MAL1.7.3.zip

      # Enable the datapack on startup and confirm it in the log
      RCON_CMDS_STARTUP: |
        datapack enable "file/AllTheMons" last
        datapack list enabled

      # Distribute the AllTheMons resource pack to clients
      RESOURCE_PACK: "https://cdn.modrinth.com/data/qoL4kNxC/versions/4i8KszCj/CCC_MAL1.7.3.zip"
      RESOURCE_PACK_SHA1: "A1C36CD993A8DA1A2450CBEBD84617370282E874"

      # RCON access for startup commands
      ENABLE_RCON: "TRUE"
      RCON_PASSWORD: "poopscoop2"
    volumes:
      - ./data:/data
    restart: no
    stop_grace_period: 2m
