name: Release mrpack & update latest.json

on:
  push:
    tags:
      - "v*.*.*"   # e.g. v1.0.0
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to create (e.g., v1.2.3)"
        required: true
        type: string

permissions:
  contents: write  # needed for releases + pushing latest.json

env:
  PACK_FILE: "BronnyPack.mrpack"
  DEFAULT_BRANCH: "main"   # change if your default branch differs

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      TAG_NAME: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref_name }}
    steps:
      - name: Checkout (commit)
        uses: actions/checkout@v4

      - name: Verify artifact exists at repo root
        run: |
          test -f "${PACK_FILE}" || (echo "Missing ${PACK_FILE} at repo root" && exit 1)

      - name: Compute checksums
        id: sums
        run: |
          SHA256=$(sha256sum "${PACK_FILE}" | awk '{print $1}')
          SIZE=$(stat -c%s "${PACK_FILE}")
          echo "sha256=$SHA256" >> "$GITHUB_OUTPUT"
          echo "size=$SIZE"     >> "$GITHUB_OUTPUT"

      - name: Create/Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.TAG_NAME }}
          target_commitish: ${{ github.sha }}
          draft: false
          prerelease: false
          # attach the mrpack from the repo root
          files: |
            ${{ env.PACK_FILE }}

      # Write latest.json on the DEFAULT_BRANCH (checked out to a separate path)
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.DEFAULT_BRANCH }}
          path: mainBranch

      - name: Write latest.json for Prism Launcher
        env:
          TAG_NAME: ${{ env.TAG_NAME }}
        run: |
          TAG="${TAG_NAME}"
          OWNER="${{ github.repository_owner }}"
          REPO="${GITHUB_REPOSITORY#*/}"
          DL_URL="https://github.com/${OWNER}/${REPO}/releases/download/${TAG}/${PACK_FILE}"

          cat > mainBranch/latest.json <<EOF
          {
            "formatVersion": 1,
            "name": "BronnyPack",
            "version": "${TAG}",
            "files": [
              {
                "url": "${DL_URL}",
                "sha256": "${{ steps.sums.outputs.sha256 }}",
                "size": ${{ steps.sums.outputs.size }},
                "primary": true
              }
            ],
            "dependencies": {}
          }
          EOF

          echo "latest.json:"
          cat mainBranch/latest.json

      - name: Commit latest.json to default branch
        run: |
          cd mainBranch
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add latest.json
          git commit -m "chore: update latest.json for ${GITHUB_REF_NAME}" || echo "No changes to commit"
          git push origin HEAD:refs/heads/${{ env.DEFAULT_BRANCH }}


  create_tag:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Create tag on current default-branch HEAD
        env:
          TAG: ${{ inputs.tag }}
          SHA: ${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/git/refs \
            -d "{\"ref\":\"refs/tags/${TAG}\",\"sha\":\"${SHA}\"}"


